## Updating a new patient entity
PUT http://localhost:4000/patients/e7663bfb-1b45-495c-92f6-84eb2b584520
Content-Type: application/json

{
  "name" : "Yashodh",
  "email" : "ym@gmail.com",
  "address" : "123 main street",
  "dateOfBirth" : "2002-09-09",

}
##